/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpwn;

/**
 *
 * @author gydokosten
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectTabPane = new javax.swing.JTabbedPane();
        CustomCodeTab = new javax.swing.JPanel();
        ExecuteCustomCodeButton = new javax.swing.JButton();
        CustomCodeTextScrollPane = new javax.swing.JScrollPane();
        CustomCodeTextArea = new javax.swing.JTextArea();
        CustomCodeClearButton = new javax.swing.JButton();
        DatabasePanel = new javax.swing.JPanel();
        DatabaseLabel = new javax.swing.JLabel();
        DatabaseClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Pwn");

        ExecuteCustomCodeButton.setText("Execute");

        CustomCodeTextArea.setColumns(20);
        CustomCodeTextArea.setRows(5);
        CustomCodeTextScrollPane.setViewportView(CustomCodeTextArea);

        CustomCodeClearButton.setText("Clear");
        CustomCodeClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomCodeClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomCodeTabLayout = new javax.swing.GroupLayout(CustomCodeTab);
        CustomCodeTab.setLayout(CustomCodeTabLayout);
        CustomCodeTabLayout.setHorizontalGroup(
            CustomCodeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomCodeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomCodeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomCodeTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(CustomCodeTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CustomCodeClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExecuteCustomCodeButton)))
                .addContainerGap())
        );
        CustomCodeTabLayout.setVerticalGroup(
            CustomCodeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomCodeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomCodeTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomCodeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExecuteCustomCodeButton)
                    .addComponent(CustomCodeClearButton))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        ProjectTabPane.addTab("Execute", CustomCodeTab);

        DatabaseLabel.setText("Loading...");
        DatabaseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DatabaseLabel.setSize(new java.awt.Dimension(62, 16));
        DatabaseLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        DatabaseClearButton.setText("Clear");
        DatabaseClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatabasePanelLayout = new javax.swing.GroupLayout(DatabasePanel);
        DatabasePanel.setLayout(DatabasePanelLayout);
        DatabasePanelLayout.setHorizontalGroup(
            DatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabasePanelLayout.createSequentialGroup()
                .addGroup(DatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatabasePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(DatabaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addGroup(DatabasePanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(DatabaseClearButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        DatabasePanelLayout.setVerticalGroup(
            DatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabasePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(DatabaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatabaseClearButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ProjectTabPane.addTab("Database", DatabasePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectTabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectTabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomCodeClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomCodeClearButtonActionPerformed
        // TODO add your handling code here:
       // this.CustomCodeTextArea.
       System.out.println("Clearing");
       this.CustomCodeTextArea.setText("");
    }//GEN-LAST:event_CustomCodeClearButtonActionPerformed

    private void DatabaseClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseClearButtonActionPerformed
        // TODO add your handling code here:
        ProjectPwn.clearDatabase();
        System.out.println("Clearing post database");
        //clear array(list) used for storing postback data
    }//GEN-LAST:event_DatabaseClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomCodeClearButton;
    private javax.swing.JPanel CustomCodeTab;
    public javax.swing.JTextArea CustomCodeTextArea;
    private javax.swing.JScrollPane CustomCodeTextScrollPane;
    private javax.swing.JButton DatabaseClearButton;
    public javax.swing.JLabel DatabaseLabel;
    public javax.swing.JPanel DatabasePanel;
    public javax.swing.JButton ExecuteCustomCodeButton;
    private javax.swing.JTabbedPane ProjectTabPane;
    // End of variables declaration//GEN-END:variables
}
